# Generated by Django 3.0.5 on 2020-04-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20200412_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(null=True, upload_to='property/'),
        ),
    ]
